/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package study;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * アプリケーションメインクラス実行
 * @author イッシー
 *
 */
@SpringBootApplication
public class App {

    /** 
     * アプリケーション実行
     * @param args 起動時に渡すパラメータ
     */
    public static void main(String[] args) {
    	SpringApplication.run(App.class, args);
    }   
}
