/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package study

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App()

        when:
        def result = app.greeting

        then:
        result != null
    }

    def "初めてのspockでのテスト"() {

	setup:
	def app = new App()

	expect:
	app.tasizan(param1, param2) == result

	where:
	param1 | param2 || result
	0      | 1      || 1 
	

    }
	
    def "モックテスト"() {
	setup:
	def app = Mock(App)

    }



}
